### ISSUE TITLE
Installing vagrant-docker-compose plugin fails

### ISSUE THREAD

**Issue by EIrwin** [leighmcculloch/vagrant-docker-compose#4]
I get the following error when running the vagrant plugin install command...

```
vagrant plugin install vagrant-docker-compose
```

```
Installing the 'vagrant-docker-compose' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:502:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from extconf.rb:16:in `<main>'


Gem files will remain installed in /Users/Me/.vagrant.d/gems/gems/ffi-1.9.10 for inspection.
Results logged to /Users/Me/.vagrant.d/gems/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

**Comment by leighmcculloch** [comment]
@EIrwin can run `gem install ffi -v '1.9.10'` and share the output?

**Comment by leighmcculloch** [comment]
@EIrwin alternatively can you try installing another vagrant plugin to rule out whether it's a general plugin installation issue or an issue with this plugin? e.g. try installing vagrant-exec if you don't have it.

**Comment by leighmcculloch** [comment]
Closing as this issue has become stale. Please reopen if this is still an active problem, and if you found a solution, please share it.
